### PR TITLE
Remove harmful terms from ca_extend

### PR DESCRIPTION
**Pull request by gavindidrichsen**
Change all references master => primary including:
* change master to primary and compile_masters to compilers
* rename ca_extend::extend_ca_cert's input parameter from compile_masters to compilers
* rename the task configure_master to configure_primary

**NOTE**: leave the external reference to deploy_pe::provision_master until deploy_pe module is changed as well.

Signed-off-by: Gavin Didrichsen <gavin.didrichsen@gmail.com>

### CODE REVIEW

**Review by MartyEwings — COMMENTED** [review]
@gavindidrichsen looks good to me, ill leave it to @m0dular for final approval since its his child! Just for future reference REFERENCE.MD is autogenerated from the content of the code comments on release, so while it doesn't matter if you update it manually, its also not required so long as you update the comments in the tasks/plans and manifests

**Comment by gavindidrichsen** [comment]
Do the following manual tests using bolt on my Mac to verify usage:

* Verify the new "compilers" parameter on ca_extend::extend_ca_cert is displayed in usage
* Verify the new "compilers" parameter on ca_extend::extend_ca_cert is working
* Verify new ca_extend::configure_primary task (renamed from ca_extend::configure_master) is working:

### Verify the new "compilers" parameter on ca_extend::extend_ca_cert is displayed in usage

```bash
➜  creating_primaries git:(master) ✗ bolt plan show ca_extend::extend_ca_cert
ca_extend::extend_ca_cert
  Plan that extends the Puppet CA certificate and configures the primary Puppet server
  and Compilers to use the extended certificate.

Usage
  bolt plan run ca_extend::extend_ca_cert [compilers=<value>]
  [regen_primary_cert=<value>] [ssldir=<value>] targets=<value>

Parameters
  compilers  Optional[TargetSpec]
    Optional comma separated list of compilers to upload the certificate to
    Default: undef

  regen_primary_cert  Any
    Whether to also regenerate the agent certificate of the primary Puppet server
    Default: false

  ssldir  Any
    Location of the ssldir on disk
    Default: '/etc/puppetlabs/puppet/ssl'

  targets  TargetSpec
    The target node on which to run the plan.  Should be the primary Puppet server

Module
  /Users/gavin.didrichsen/Documents/@REFERENCE/github/app/tools/puppet/products/bolt/examples/platform9/creating_primaries/.modules/ca_extend
➜  creating_primaries git:(master) ✗ 
```

### Verify the new "compilers" parameter on ca_extend::extend_ca_cert is working 

Prove that the new "compilers" plan parameter is being injected ok, nothing more: change the ca_extend::extend_ca_cert to contain only the following:

```ruby
plan ca_extend::extend_ca_cert(
  TargetSpec $targets,
  Optional[TargetSpec] $compilers = undef,
  $ssldir                               = '/etc/puppetlabs/puppet/ssl',
  $regen_primary_cert                   = false,
) {
  out::message("INFO: Stopping Puppet services on ${targets}")
  out::message("INFO: Stopping Puppet services on compilers (${compilers})")
}
```

Run the plan and verify:

```bash
➜  creating_primaries git:(master) ✗ bolt plan run ca_extend::extend_ca_cert --targets=p9.p.19 compilers=p9.r.19,p9-dr-a03
Starting: plan ca_extend::extend_ca_cert
INFO: Stopping Puppet services on p9.p.19
INFO: Stopping Puppet services on compilers (p9.r.19,p9-dr-a03)
Finished: plan ca_extend::extend_ca_cert in 0.01 sec
Plan completed successfully with no result
➜  creating_primaries git:(master) ✗ 
```


### Verify new ca_extend::configure_primary task (renamed from ca_extend::configure_master) is working:

As I don't actually want this task to do anything on my primary...

* Add some debug code at the top to verify the input parameters and
* exit 0 before any of the actual work is done


```bash
# add the following debug code at the top
echo "################# Doing the primary"
echo ">>>${PT_new_cert}"
echo ">>>${PT_regen_primary_cert}"
success '{ "status": "success" }'
exit 0


# run the bolt command
➜  creating_primaries git:(master) ✗ bolt task run ca_extend::configure_primary new_cert="/super/new/cert" regen_primary_cert=true --targets=p9.r.19
Started on p9.r.19...
The 'stream' option is experimental, and might include breaking changes between minor versions. [ID: stream_experimental]
[p9.r.19] out: 0
[p9.r.19] out: ################# Doing the primary
[p9.r.19] out: >>>/super/new/cert
[p9.r.19] out: >>>true
[p9.r.19] err: /tmp/88ac05e7-61bd-462c-a41d-1e3b5e02d7d9/ca_extend/tasks/configure_primary.sh: line 6: success: command not found
Finished on p9.r.19:
  ################# Doing the primary
  >>>/super/new/cert
  >>>true
Successful on 1 target: p9.r.19
Ran on 1 target in 11.12 sec
➜  creating_primaries git:(master) ✗ 
```

**Comment by m0dular** [comment]
@gavindidrichsen Looks good, but like Marty mentioned we auto-generate the reference file now.  We have those changes in this branch already, so could we undo your changes to that file?  With your branch checked out:

```
git reset HEAD^ -- REFERENCE.md
git commit
git push
```

Then we should be good to merge.

**Review by m0dular — CHANGES_REQUESTED** [review]
I have to leave a review comment apparently, so please revert the `REFERENCE.md` changes that I mentioned.  Otherwise, looks great.

**Comment by gavindidrichsen** [comment]
> Marty mentioned we auto-generate the [REFERENCE.md] file now...so could we undo your changes to that file?

Thanks @m0dular, @MartyEwings:  I've reverted the REFERENCE.md changes and squashed commits, so hopefully this is good to go now!

**Review by m0dular — APPROVED** [review]

**Pull request merged**
